const express = require("express");
const router = express.Router();

// --- Mock Device Data (Beta Demo) ---
const mockDevices = [
  // Audio ---
  {
    _id: "m1",
    deviceName: "Yamaha QL5 Console",
    ip: "10.0.0.11",
    mac: "00:1A:4B:11:2C:AA",
    make: "Yamaha",
    model: "QL5",
    firmwareVersion: "5.10",
    serialNum: "YQ5-1001",
    location: "FOH",
    room: "Main Sanctuary",
    group: "Audio",
    status: "Online",
  },
  {
    _id: "m2",
    deviceName: "TF Rack Mixer",
    ip: "10.0.0.12",
    mac: "00:1A:4B:11:2C:AB",
    make: "Yamaha",
    model: "TF-Rack",
    firmwareVersion: "5.00",
    serialNum: "TFR-2231",
    location: "Booth",
    room: "Youth Room",
    group: "Audio",
    status: "Online",
  },
  {
    _id: "m3",
    deviceName: "Rio 3224-D2 Stage Box",
    ip: "10.0.0.13",
    mac: "00:1A:4B:11:2C:AC",
    make: "Yamaha",
    model: "Rio 3224-D2",
    firmwareVersion: "4.80",
    serialNum: "RIO-4432",
    location: "Stage Left",
    room: "Main Sanctuary",
    group: "Audio",
    status: "Online",
  },
  {
    _id: "m4",
    deviceName: "Shure Axient Receiver",
    ip: "10.0.0.14",
    mac: "00:1A:4B:11:2C:AD",
    make: "Shure",
    model: "ADX5D",
    firmwareVersion: "2.12.3",
    serialNum: "SHU-8883",
    location: "Rack 2",
    room: "Audio Control",
    group: "Audio",
    status: "Offline",
  },
  {
    _id: "m5",
    deviceName: "Q-SYS Core Nano",
    ip: "10.0.0.15",
    mac: "00:1A:4B:11:2C:AE",
    make: "QSC",
    model: "Core Nano",
    firmwareVersion: "9.7.0",
    serialNum: "QSC-1010",
    location: "Rack 1",
    room: "Control Booth",
    group: "Audio",
    status: "Online",
  },

  //  Video ---
  {
    _id: "m6",
    deviceName: "ATEM 4 M/E Broadcast Studio 4K",
    ip: "10.0.0.21",
    mac: "00:1B:55:22:3D:BA",
    make: "Blackmagic Design",
    model: "ATEM 4 M/E",
    firmwareVersion: "9.0.1",
    serialNum: "BMD-2033",
    location: "Control Room",
    room: "Broadcast Suite",
    group: "Video",
    status: "Online",
  },
  {
    _id: "m7",
    deviceName: "HyperDeck Studio HD Plus",
    ip: "10.0.0.22",
    mac: "00:1B:55:22:3D:BB",
    make: "Blackmagic Design",
    model: "HyperDeck HD Plus",
    firmwareVersion: "9.0.1",
    serialNum: "BMD-2394",
    location: "Control Room",
    room: "Broadcast Suite",
    group: "Video",
    status: "Offline",
  },
  {
    _id: "m8",
    deviceName: "Sony PTZ Camera 1",
    ip: "10.0.0.23",
    mac: "00:1B:55:22:3D:BC",
    make: "Sony",
    model: "BRC-X1000",
    firmwareVersion: "2.2.0",
    serialNum: "SN-PTZ-100",
    location: "Catwalk",
    room: "Main Sanctuary",
    group: "Video",
    status: "Online",
  },
  {
    _id: "m9",
    deviceName: "Sony PTZ Camera 2",
    ip: "10.0.0.24",
    mac: "00:1B:55:22:3D:BD",
    make: "Sony",
    model: "BRC-X1000",
    firmwareVersion: "2.2.0",
    serialNum: "SN-PTZ-101",
    location: "Balcony",
    room: "Main Sanctuary",
    group: "Video",
    status: "Online",
  },
  {
    _id: "m10",
    deviceName: "DeckLink Recorder",
    ip: "10.0.0.25",
    mac: "00:1B:55:22:3D:BE",
    make: "Blackmagic",
    model: "DeckLink 8K Pro",
    firmwareVersion: "12.5.0",
    serialNum: "DLK-1111",
    location: "Workstation 3",
    room: "Broadcast Suite",
    group: "Video",
    status: "Offline",
  },

  // 💡 Lighting
  {
    _id: "m11",
    deviceName: "Lighting Console",
    ip: "10.0.0.31",
    mac: "00:1C:66:33:4E:CA",
    make: "MA Lighting",
    model: "GrandMA3",
    firmwareVersion: "1.9.3.4",
    serialNum: "MA3-3098",
    location: "FOH",
    room: "Main Sanctuary",
    group: "Lighting",
    status: "Online",
  },
  {
    _id: "m12",
    deviceName: "DMX Node 1",
    ip: "10.0.0.32",
    mac: "00:1C:66:33:4E:CB",
    make: "Pathway Connectivity",
    model: "Pathport",
    firmwareVersion: "2.1.4",
    serialNum: "PP-0009",
    location: "Catwalk",
    room: "Main Sanctuary",
    group: "Lighting",
    status: "Online",
  },
  {
    _id: "m13",
    deviceName: "DMX Node 2",
    ip: "10.0.0.33",
    mac: "00:1C:66:33:4E:CC",
    make: "Pathway Connectivity",
    model: "Pathport",
    firmwareVersion: "2.1.4",
    serialNum: "PP-0010",
    location: "Back Wall",
    room: "Main Sanctuary",
    group: "Lighting",
    status: "Offline",
  },
  {
    _id: "m14",
    deviceName: "House Light Controller",
    ip: "10.0.0.34",
    mac: "00:1C:66:33:4E:CD",
    make: "Lutron",
    model: "DMX Gateway",
    firmwareVersion: "3.0.2",
    serialNum: "LUT-4450",
    location: "Lighting Booth",
    room: "Control Booth",
    group: "Lighting",
    status: "Online",
  },

  // Network + Misc ----
  {
    _id: "m15",
    deviceName: "Cisco Core Switch",
    ip: "10.0.0.40",
    mac: "00:1E:77:44:5F:DA",
    make: "Cisco",
    model: "CBS350-8P",
    firmwareVersion: "3.2.1",
    serialNum: "CSC-1142",
    location: "Rack 1",
    room: "Server Room",
    group: "Network",
    status: "Online",
  },
  {
    _id: "m16",
    deviceName: "Netgear Backup Switch",
    ip: "10.0.0.41",
    mac: "00:1E:77:44:5F:DB",
    make: "Netgear",
    model: "M4250",
    firmwareVersion: "2.0.5",
    serialNum: "NET-8841",
    location: "Rack 3",
    room: "Broadcast Suite",
    group: "Network",
    status: "Online",
  },
  {
    _id: "m17",
    deviceName: "UPS Power Monitor",
    ip: "10.0.0.42",
    mac: "00:1E:77:44:5F:DC",
    make: "APC",
    model: "SmartUPS 3000",
    firmwareVersion: "1.0.4",
    serialNum: "UPS-2223",
    location: "Rack 1",
    room: "Server Room",
    group: "Power",
    status: "Online",
  },
  {
    _id: "m18",
    deviceName: "Dante Controller",
    ip: "10.0.0.43",
    mac: "00:1E:77:44:5F:DD",
    make: "Audinate",
    model: "Dante Controller",
    firmwareVersion: "4.10.0",
    serialNum: "DNT-3244",
    location: "Laptop",
    room: "Audio Booth",
    group: "Network",
    status: "Online",
  },
  {
    _id: "m19",
    deviceName: "NDI Camera Encoder",
    ip: "10.0.0.44",
    mac: "00:1E:77:44:5F:DE",
    make: "BirdDog",
    model: "Flex 4K",
    firmwareVersion: "1.1.0",
    serialNum: "BD-8842",
    location: "Camera 3",
    room: "Main Sanctuary",
    group: "Video",
    status: "Offline",
  },
  {
    _id: "m20",
    deviceName: "Wireless Access Point",
    ip: "10.0.0.45",
    mac: "00:1E:77:44:5F:DF",
    make: "Ubiquiti",
    model: "UniFi 6 Pro",
    firmwareVersion: "7.0.2",
    serialNum: "UBI-9982",
    location: "Ceiling 2",
    room: "Broadcast Suite",
    group: "Network",
    status: "Online",
  },
  {
    _id: "m21",
    deviceName: "Streaming Encoder",
    ip: "10.0.0.46",
    mac: "00:1E:77:44:5F:E0",
    make: "Epiphan",
    model: "Pearl-2",
    firmwareVersion: "5.3.0",
    serialNum: "EPI-2210",
    location: "Rack 2",
    room: "Broadcast Suite",
    group: "Video",
    status: "Online",
  },
  {
    _id: "m22",
    deviceName: "Rackmount Server",
    ip: "10.0.0.47",
    mac: "00:1E:77:44:5F:E1",
    make: "Dell",
    model: "PowerEdge R640",
    firmwareVersion: "3.0.3",
    serialNum: "DEL-9000",
    location: "Rack 1",
    room: "Server Room",
    group: "Infrastructure",
    status: "Online",
  },
  {
    _id: "m23",
    deviceName: "Stage Display Controller",
    ip: "10.0.0.48",
    mac: "00:1E:77:44:5F:E2",
    make: "Renewed Vision",
    model: "ProPresenter 7",
    firmwareVersion: "7.15",
    serialNum: "PRO-7184",
    location: "FOH",
    room: "Main Sanctuary",
    group: "Video",
    status: "Online",
  },
  {
    _id: "m24",
    deviceName: "Lighting Gateway",
    ip: "10.0.0.49",
    mac: "00:1E:77:44:5F:E3",
    make: "ETC",
    model: "Net3 Gateway",
    firmwareVersion: "1.2.3",
    serialNum: "ETC-1098",
    location: "Catwalk",
    room: "Main Sanctuary",
    group: "Lighting",
    status: "Offline",
  },
  {
    _id: "m25",
    deviceName: "Network Router",
    ip: "10.0.0.50",
    mac: "00:1E:77:44:5F:E4",
    make: "Ubiquiti",
    model: "Dream Machine Pro",
    firmwareVersion: "3.0.0",
    serialNum: "UBI-7711",
    location: "Rack 1",
    room: "Server Room",
    group: "Network",
    status: "Online",
  },
];

// GET /mock/devices
router.get("/devices", (req, res) => {
  res.status(200).json(mockDevices);
});

module.exports = router;
